- name: Upload the crictl.yaml file
  become: true
  copy:
    src: crictl.yaml
    dest: /etc/crictl.yaml

- name: Install crictl
  become: true
  shell:
    creates: /usr/local/bin/crictl
    cmd: >-
      curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ crictl_version }}/crictl-{{ crictl_version }}-linux-amd64.tar.gz --output crictl-{{ crictl_version }}-linux-amd64.tar.gz
      && tar zxvf crictl-{{ crictl_version }}-linux-amd64.tar.gz -C /usr/local/bin
      && rm -f crictl-{{ crictl_version }}-linux-amd64.tar.gz

- name: Ensure /etc/kubernetes exists
  become: true
  file:
    path: /etc/kubernetes
    state: directory

- name: Upload the cloud-config
  become: true
  copy:
    dest: /etc/kubernetes/cloud-config
    content: "{{ lookup('env', 'KUBE_CLOUD_CONF') | b64decode }}"

- name: Make a copy of the cloud-config 
  become: true
  shell:
    creates: /etc/kubernetes/cloud.conf
    cmd: cp /etc/kubernetes/cloud-config /etc/kubernetes/cloud.conf