---
- hosts: controllers[0]
  collections:
    - kubernetes.core
  tasks:
    - name: Install OpenShift
      pip:
        name: openshift
        state: present
    - name: Create a secret with the cloud.config
      k8s:
        state: present
        definition:
          kind: Secret
          apiVersion: v1
          metadata:
            name: cloud-config
            namespace: kube-system
          data:
            cloud.conf: "{{ lookup('env', 'KUBE_CLOUD_CONF') }}"
    - name: Some K8S distributions expect a cloud.conf in /etc/kubernetes
      become: yes
      copy:
        dest: /etc/kubernetes/cloud.conf
        content: "{{ lookup('env', 'KUBE_CLOUD_CONF') | b64decode }}"
  