---
- hosts: nodes
  collections:
    - kubernetes.core
  tasks:
    - name: Install Python3 and pip
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      become: true
      loop:
        - python3
        - python3-pip
        - nfs-common

    - name: Install openshift
      pip:
        name: openshift
        state: present
